# Generated by Django 2.2.15 on 2020-08-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー')),
                ('large', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.LargeCategory', verbose_name='大カテゴリー')),
                ('middle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.MiddleCategory', verbose_name='中カテゴリー')),
                ('small', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.SmallCategory', verbose_name='小カテゴリー')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.Category'),
            preserve_default=False,
        ),
    ]
