# Generated by Django 2.2.15 on 2020-08-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200830_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlecategory',
            name='large',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.LargeCategory', verbose_name='大カテゴリー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallcategory',
            name='middle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.MiddleCategory', verbose_name='中カテゴリー'),
            preserve_default=False,
        ),
    ]
